# Generated by Django 4.2.3 on 2023-07-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Genres',
            new_name='genres',
        ),
    ]
